#pragma once

#define INFOTERM_APP_NAME "InfoTerm"
#define INFOTERM_APP_VERSION "1.0.11"
#define INFOTERM_VERSION INFOTERM_APP_VERSION
#define INFOTERM_FULL_VERSION INFOTERM_APP_NAME " " INFOTERM_APP_VERSION
