#pragma once

#define INFOTERM_APP_NAME "InfoTerm"
#define INFOTERM_APP_VERSION "1.0.9"
#define INFOTERM_VERSION INFOTERM_APP_VERSION
#define INFOTERM_FULL_VERSION INFOTERM_APP_NAME " " INFOTERM_APP_VERSION
